project:
  type: website
  resources: 
    -  "files/"

website:
  title: "Philipp Jonas Kreutzer"
  back-to-top-navigation: true
  search: false
  navbar:
    right:
      - href: index.qmd#research
        text: Research
      - href: index.qmd#teaching
        text: Teaching
      - href: index.qmd#outreach
        text: Outreach
      - href: index.qmd#talks
        text: Talks


    twitter-card:
      creator: "@pjkreutzer"

format:
  pjk_theme-html: 
    toc: false



