project:
  type: website
  resources: 
    -  "files/"

website:
  title: "Philipp Jonas Kreutzer"
  navbar:
    left:
      - href: teaching.qmd
        text: teaching
      - href: outreach.qmd
        text: outreach
    
    twitter-card:
      creator: "@pj_kreutzer"

format:
  html:
    theme: [litera, styles.scss]
    toc: true



