project:
  type: website

website:
  title: "Philipp Jonas Kreutzer"
  navbar:
    left:
      - href: teaching.qmd
        text: teaching
      - href: outreach.qmd
        text: outreach

format:
  html:
    theme: [cosmo]
    css: styles.css
    toc: true



