project:
  type: website
  resources: 
    -  "files/"

website:
  title: "Philipp Jonas Kreutzer"
  navbar:
    right:
      - href: research.qmd
        text: research
      - href: teaching.qmd
        text: teaching
      - href: outreach.qmd
        text: outreach
      - href: talks.qmd
        text: talks


    twitter-card:
      creator: "@pjkreutzer"

format:
  html:
    theme: [litera, me.scss]
    toc: false



